name: Build Flutter Android

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Setup environment for Flutter build
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Java Development Kit (JDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.7'
        channel: 'stable'
        cache: true
    - name: Get Flutter dependencies
      run: flutter pub get

    # 2. Steps to place secret files needed for the build
    - name: Decode and place .env file
      run: echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env
      shell: bash
    - name: Decode and place Keystore file
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/upload-keystore.jks
      shell: bash
    - name: Decode and place key.properties file
      run: echo "${{ secrets.KEY_PROPERTIES_FILE }}" | base64 --decode > android/key.properties
      shell: bash
    - name: Decode and place google-services.json file
      run: echo "${{ secrets.GOOGLE_SERVICES_JSON_FILE }}" | base64 --decode > android/app/google-services.json
      shell: bash
    - name: Decode and place firebase.json file
      run: echo "${{ secrets.FIREBASE_JSON_FILE }}" | base64 --decode > firebase.json
      shell: bash
    - name: Decode and place firebase_options.dart file
      run: echo "${{ secrets.FIREBASE_OPTIONS_DART_FILE }}" | base64 --decode > lib/firebase_options.dart
      shell: bash

    # 3. Build the Flutter app for Android
    - name: Build Release - Universal
      run: flutter build apk --release
      working-directory: ./
    - name: Build Release - Split per ABI
      run: flutter build apk --release --split-per-abi
      working-directory: ./

    # 4. Generate Checksum files
    - name: Generate SHA256 checksums file
      run: |
        cd build/app/outputs/flutter-apk
        sha256sum app-arm64-v8a-release.apk > sha256sums.txt
        sha256sum app-armeabi-v7a-release.apk >> sha256sums.txt
        sha256sum app-release.apk >> sha256sums.txt
        sha256sum app-x86_64-release.apk >> sha256sums.txt

    # 4. Upload the build artifacts
    - name: Upload APK arm64-v8a
      uses: actions/upload-artifact@v4
      with:
        name: app-arm64-v8a-release.apk
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
    - name: Upload APK armeabi-v7a
      uses: actions/upload-artifact@v4
      with:
        name: app-armeabi-v7a-release.apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    - name: Upload APK release
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Upload APK x86_64
      uses: actions/upload-artifact@v4
      with:
        name: app-x86_64-release.apk
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk

    # 5. Upload Checksum Files
    - name: Upload SHA256 Checksum File
      uses: actions/upload-artifact@v4
      with:
        name: sha256sums.txt
        path: build/app/outputs/flutter-apk/sha256sums.txt